export const MOCK_FEED = [
  {
    picture_id: '942c426f-c44e-43e0-aa42-22b8227a496b',
    drink_name: 'Lotlux',
    rating: 3.7,
    glassware: 'model',
    description: 'Up-sized real-time alliance',
    location: 'Khatsyezhyna',
    username: 'cmailey0',
  },
  {
    picture_id: '04c33d68-4486-4456-bf72-028e05b010f5',
    drink_name: 'Greenlam',
    rating: 3.7,
    glassware: 'Realigned',
    description: 'Quality-focused next generation projection',
    location: 'Bous',
    username: 'slabrow1',
  },
  {
    picture_id: '6dd3aacf-018d-40e5-8f54-7b50c7de4e9a',
    drink_name: 'Bitwolf',
    rating: 1.0,
    glassware: 'focus group',
    description: 'Centralized full-range monitoring',
    location: 'Sagara',
    username: 'pwear2',
  },
  {
    picture_id: '70ce4a05-9351-4f70-a73a-da4a3bc46b85',
    drink_name: 'Tempsoft',
    rating: 4.0,
    glassware: 'value-added',
    description: 'Distributed reciprocal initiative',
    location: 'Toulouse',
    username: 'grushmare3',
  },
  {
    picture_id: '080c4296-1cd7-4b59-a69a-4220a3d9cc1d',
    drink_name: 'Daltfresh',
    rating: 4.7,
    glassware: 'Cross-platform',
    description: 'Expanded uniform Graphical User Interface',
    location: 'Gafsa',
    username: 'yullyott4',
  },
  {
    picture_id: '8595aaa5-60cd-44e0-bdcf-85fc4d12a85c',
    drink_name: 'Cardguard',
    rating: 3.5,
    glassware: '24/7',
    description: 'Enterprise-wide needs-based capability',
    location: 'Smyga',
    username: 'mburburough5',
  },
  {
    picture_id: '31590b68-8234-4fb8-b2ea-59898c534d33',
    drink_name: 'Zamit',
    rating: 1.4,
    glassware: 'bifurcated',
    description: 'Reactive zero tolerance database',
    location: 'Chotepe',
    username: 'tspykings6',
  },
  {
    picture_id: 'a92945e9-bf80-4930-b3d8-7d6b914e5975',
    drink_name: 'Tempsoft',
    rating: 3.0,
    glassware: 'database',
    description: 'Right-sized 6th generation definition',
    location: 'Bom Sucesso',
    username: 'tsavidge7',
  },
  {
    picture_id: '713bba95-e890-49d0-9588-fb39fe3d21a2',
    drink_name: 'Cardguard',
    rating: 1.4,
    glassware: 'task-force',
    description: 'Public-key heuristic pricing structure',
    location: 'Jauja',
    username: 'rseagrove8',
  },
  {
    picture_id: 'f665bbb0-2821-41bc-8a81-9d05fca713b8',
    drink_name: 'Domainer',
    rating: 1.7,
    glassware: 'Down-sized',
    description: 'Devolved intangible application',
    location: 'Karadaglije',
    username: 'mmckeaney9',
  },
];
